export function renderEditableRecordingPage(recordingSessionId) {
  return `<!doctype html>
<html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Browsy Recording ${escapeHtml(recordingSessionId)}</title>
<style>
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f7f7f8;color:#111827;margin:0}main{max-width:1180px;margin:0 auto;padding:32px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:20px;margin:16px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.pill{display:inline-block;border-radius:999px;padding:4px 10px;background:#eef2ff;color:#3730a3;font-size:12px;margin:2px 4px 2px 0}button,a.button{border:0;border-radius:10px;padding:10px 14px;background:#111827;color:white;cursor:pointer;text-decoration:none;display:inline-block;margin:4px 6px 4px 0}button.secondary,a.secondary{background:#4b5563}button.ghost{background:#e5e7eb;color:#111827}button.danger{background:#991b1b}button:disabled{opacity:.45;cursor:not-allowed}pre,textarea{width:100%;box-sizing:border-box;background:#0b1020;color:#d1e7ff;border-radius:12px;padding:12px;overflow:auto}textarea{min-height:160px;border:0;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #e5e7eb;padding:8px;vertical-align:top}.muted{color:#6b7280}.ok{color:#047857;font-weight:700}.warn{color:#b45309;font-weight:700}.bad{color:#991b1b;font-weight:700}input{width:100%;box-sizing:border-box;border:1px solid #d1d5db;border-radius:8px;padding:8px}input[type=checkbox]{width:auto}.small{font-size:12px}.urlcell{min-width:360px}.nowrap{white-space:nowrap}
</style></head><body><main>
<h1>Browsy Recording Session</h1><p class="muted">Generic app-initiated recording bridge. Edit setup, save, then start recording.</p>
<section class="card" data-testid="recording-summary"><div class="grid"><div><strong>Session</strong><br><span id="recordingSessionId">${escapeHtml(recordingSessionId)}</span></div><div><strong>Status</strong><br><span id="status" data-testid="recording-status">Loading...</span></div><div><strong>App</strong><br><span id="app"></span></div><div><strong>Workflow</strong><br><span id="workflow"></span></div></div></section>
<section class="card"><h2>Setup</h2><div class="grid"><label>Auth profile / SSO group<br><input id="authProfileId" data-testid="auth-profile-id" placeholder="e.g. d2l-okta-sso" /></label><label>Callback URL<br><input id="callbackUrl" data-testid="callback-url" placeholder="optional" /></label></div><p class="muted small">Use one shared auth profile for Okta-backed apps. Example: <code>d2l-okta-sso</code>.</p><button id="saveSetupBtn" data-testid="save-setup-button">Save Setup</button><span id="setupValidation" data-testid="setup-validation" class="muted"></span></section>
<section class="card"><h2>Actions</h2><button id="checkAuthBtn" data-testid="check-auth-button" class="ghost">Check Auth</button><button id="startRecordingBtn" data-testid="start-recording-button">Start Recording</button><button id="stopRecordingBtn" data-testid="stop-recording-button" class="secondary">Stop Recording</button><button id="importWorkflowBtn" data-testid="import-workflow-button">Import Workflow</button><button id="viewContractBtn" data-testid="view-contract-button" class="ghost">View Contract</button><a id="recorderLink" data-testid="recorder-link" class="button secondary" target="_blank" rel="noreferrer">Open Recorder</a><div id="actionResult" data-testid="action-result" class="muted"></div></section>
<section class="card"><h2>Tabs</h2><table data-testid="tabs-table"><thead><tr><th>ID</th><th>Title</th><th class="urlcell">URL</th><th>Site ID</th><th>Auth</th><th>Remove</th></tr></thead><tbody id="tabsBody"></tbody></table><button id="addTabBtn" class="ghost" data-testid="add-tab-button">Add Tab</button></section>
<section class="card"><h2>Payload Fields</h2><div id="payloadFields" data-testid="payload-fields"></div></section>
<section class="card"><h2>File Bindings</h2><div id="fileBindings" data-testid="file-bindings"></div></section>
<section class="card"><h2>Expected Outputs</h2><div id="expectedOutputs" data-testid="expected-outputs"></div></section>
<section class="card"><h2>Human Checkpoints</h2><div id="humanCheckpoints" data-testid="human-checkpoints"></div></section>
<section class="card"><h2>Observation / Events</h2><p class="muted">Paste observed data here for manual stop/import flows. If blank, Browsy uses the real recorder events captured for this session.</p><textarea id="observationInput" data-testid="observation-input" placeholder='{"schemaVersion":"browsy.observation.v1", ...}'></textarea></section>
<section class="card"><h2>Contract / Result</h2><pre id="contractOutput" data-testid="contract-output">{}</pre></section>
</main><script>
const recordingSessionId=${JSON.stringify(recordingSessionId)};let currentRecording=null;let tabsDraft=[];let actionInFlight=false;
function el(id){return document.getElementById(id)}
function isRecordingActive(){return currentRecording&&currentRecording.status==='recording'}
function isImported(){return currentRecording&&currentRecording.status==='imported'}
function isPlaceholderUrl(url){return !url||/PASTE_|YOUR_|_HERE/i.test(url)||!(url.startsWith('http://')||url.startsWith('https://')||url.startsWith('about:')||url.startsWith('data:'))}
function renderList(target,items,formatter){target.innerHTML='';if(!items||!items.length){target.innerHTML='<span class="muted">None</span>';return}for(const item of items){const span=document.createElement('span');span.className='pill';span.textContent=formatter(item);target.appendChild(span)}}
async function api(path,options={}){const res=await fetch(path,options);const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false){const err=new Error(data.error||res.statusText||'Request failed');err.data=data;err.status=res.status;throw err}return data}
function parseObservation(){const raw=el('observationInput').value.trim();if(!raw)return{};const parsed=JSON.parse(raw);return parsed.events?{events:parsed.events,observation:parsed.observation}:{observation:parsed}}
function tabRow(tab,index){const invalid=isPlaceholderUrl(tab.url);const disabled=isRecordingActive()||isImported()?' disabled':'';return '<tr data-tab-index="'+index+'"><td><input data-field="id" value="'+escapeAttr(tab.id||('tab'+(index+1)))+'"'+disabled+'></td><td><input data-field="title" value="'+escapeAttr(tab.title||'')+'"'+disabled+'></td><td><input data-field="url" value="'+escapeAttr(tab.url||'')+'" placeholder="https://..."'+disabled+'><div data-url-status class="small '+(invalid?'bad':'muted')+'">'+(invalid?'Enter a real URL before Start Recording':'OK')+'</div></td><td><input data-field="siteId" value="'+escapeAttr(tab.siteId||'')+'" placeholder="salesforce"'+disabled+'></td><td class="nowrap"><input type="checkbox" data-field="requiresAuth" '+(tab.requiresAuth?'checked':'')+disabled+'> Required</td><td><button class="danger" data-remove-tab="'+index+'"'+disabled+'>Remove</button></td></tr>'}
function syncTabsFromInputs(){const rows=[...document.querySelectorAll('#tabsBody tr')];tabsDraft=rows.map((row,index)=>{const get=f=>row.querySelector('[data-field="'+f+'"]');return {id:(get('id')?.value||('tab'+(index+1))).trim(),title:(get('title')?.value||'').trim(),url:(get('url')?.value||'').trim(),siteId:(get('siteId')?.value||'').trim(),requiresAuth:!!get('requiresAuth')?.checked}})}
function renderTabs(){const body=el('tabsBody');body.innerHTML=tabsDraft.map(tabRow).join('');body.querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>{syncTabsFromInputs();updateRowUrlStatuses();validateSetup()}));body.querySelectorAll('[data-remove-tab]').forEach(btn=>btn.onclick=()=>{syncTabsFromInputs();tabsDraft.splice(Number(btn.dataset.removeTab),1);renderTabs();validateSetup()})}
function updateRowUrlStatuses(){document.querySelectorAll('#tabsBody tr').forEach(row=>{const url=row.querySelector('[data-field="url"]')?.value?.trim()||'';const status=row.querySelector('[data-url-status]');const invalid=isPlaceholderUrl(url);if(status){status.textContent=invalid?'Enter a real URL before Start Recording':'OK';status.className='small '+(invalid?'bad':'muted')}})}
function validateSetup(){syncTabsFromInputs();updateRowUrlStatuses();const bad=tabsDraft.filter(t=>isPlaceholderUrl(t.url));let msg=bad.length?'Fix '+bad.length+' tab URL(s) before Start Recording.':'Setup looks ready.';let cls=bad.length?'bad':'ok';if(isRecordingActive()){msg='Recording is active. Click Stop Recording before editing setup or starting again.';cls='warn'}else if(isImported()){msg='Workflow already imported. Create a new session to edit setup.';cls='warn'}el('setupValidation').textContent=msg;el('setupValidation').className=cls;el('saveSetupBtn').disabled=actionInFlight||isRecordingActive()||isImported();el('startRecordingBtn').disabled=actionInFlight||bad.length>0||isRecordingActive()||isImported();el('addTabBtn').disabled=actionInFlight||isRecordingActive()||isImported();return bad.length===0&&!isRecordingActive()&&!isImported()}
async function load(){const data=await api('/api/recordings/'+encodeURIComponent(recordingSessionId));const r=data.recording;currentRecording=r;tabsDraft=((r.recordingSetup&&r.recordingSetup.tabs)||[]).map(t=>({...t}));el('status').textContent=r.status;el('status').className=r.status==='imported'?'ok':r.status==='recording'?'warn':'';el('app').textContent=(r.appName||r.appId)+' / '+r.appId;el('workflow').textContent=(r.workflowName||r.workflowId)+' / '+r.workflowId;el('recorderLink').href=r.recorderUrl||'#';el('recorderLink').textContent=r.recorderUrl?'Open Recorder':'Recorder URL unavailable';el('authProfileId').value=(r.recordingSetup&&r.recordingSetup.authProfileId)||'';el('authProfileId').disabled=isRecordingActive()||isImported();el('callbackUrl').value=r.callbackUrl||'';el('callbackUrl').disabled=isRecordingActive()||isImported();renderTabs();renderList(el('payloadFields'),Object.keys((r.payloadSchema&&r.payloadSchema.properties)||{}).map(k=>({id:k})),x=>x.id);renderList(el('fileBindings'),r.fileBindings||[],x=>x.id+' ← '+x.source);renderList(el('expectedOutputs'),r.expectedOutputs||[],x=>x.id);renderList(el('humanCheckpoints'),r.humanCheckpoints||[],x=>x.id);validateSetup()}
async function saveSetup(){if(isRecordingActive()){throw new Error('Click Stop Recording before saving setup.')}syncTabsFromInputs();const recordingSetup={...(currentRecording.recordingSetup||{}),authProfileId:el('authProfileId').value.trim(),tabs:tabsDraft};const data=await api('/api/recordings/'+encodeURIComponent(recordingSessionId)+'/setup',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({recordingSetup,callbackUrl:el('callbackUrl').value.trim()})});el('actionResult').textContent='Saved setup.';await load();return data}
async function runAction(label,fn){if(actionInFlight)return;actionInFlight=true;el('actionResult').className='warn';el('actionResult').textContent=label+'...';el('contractOutput').textContent='{}';validateSetup();try{const result=await fn();el('actionResult').className='ok';return result}catch(err){el('actionResult').className='bad';el('actionResult').textContent='Error: '+(err.message||String(err));el('contractOutput').textContent=JSON.stringify({error:err.message||String(err),status:err.status||null,details:err.data||null},null,2)}finally{actionInFlight=false;validateSetup()}}
function escapeAttr(value){return String(value||'').replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]))}
el('addTabBtn').onclick=()=>{syncTabsFromInputs();tabsDraft.push({id:'tab'+(tabsDraft.length+1),title:'',url:'',siteId:'',requiresAuth:false});renderTabs();validateSetup()};
el('saveSetupBtn').onclick=()=>runAction('Saving setup',async()=>{await saveSetup();el('actionResult').textContent='Saved setup.'});
el('checkAuthBtn').onclick=async()=>{el('actionResult').className='muted';el('actionResult').textContent='Auth requirements: '+JSON.stringify((currentRecording&&currentRecording.auth)||[])};
el('startRecordingBtn').onclick=()=>runAction('Starting recording',async()=>{if(!validateSetup()){throw new Error(isRecordingActive()?'Click Stop Recording before starting again.':'Fix tab URLs before starting.')}await saveSetup();const data=await api('/api/recordings/'+encodeURIComponent(recordingSessionId)+'/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})});el('actionResult').textContent='Recording started: '+((data.launch&&data.launch.mode)||'unknown')+' events: '+((data.active&&data.active.eventCount)||0);await load();return data});
el('stopRecordingBtn').onclick=()=>runAction('Stopping recording',async()=>{const payload=parseObservation();const data=await api('/api/recordings/'+encodeURIComponent(recordingSessionId)+'/stop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});el('actionResult').textContent='Stopped: '+data.recording.status+' events: '+((data.runtime&&data.runtime.eventCount)||0);await load();return data});
el('importWorkflowBtn').onclick=()=>runAction('Importing workflow',async()=>{const data=await api('/api/recordings/'+encodeURIComponent(recordingSessionId)+'/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({overwrite:true,autoRegisterApp:true})});el('actionResult').textContent='Imported workflowRef: '+data.workflowRef;el('contractOutput').textContent=JSON.stringify(data.contract||data.recording,null,2);await load();return data});
el('viewContractBtn').onclick=()=>runAction('Loading contract',async()=>{const data=await api('/api/recordings/'+encodeURIComponent(recordingSessionId)+'/contract');el('actionResult').textContent='Loaded contract.';el('contractOutput').textContent=JSON.stringify(data.contract,null,2);return data});
load().catch(err=>{el('actionResult').className='bad';el('actionResult').textContent=err.message});
</script></body></html>`;
}
function escapeHtml(value=''){return String(value).replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));}
