import { join } from 'path';
import { exists } from './paths.mjs';

// Artifacts that are expected in every run directory.
const EXPECTED_ARTIFACTS = [
  'run-log.json',
  'filled-fields.json',
  'skipped-fields.json',
  'errors.json',
  'screenshot-start.png',
  'screenshot-after-fill.png',
  'page-text-snapshot.txt',
  'html-snapshot.html'
];

// Generate run-review.md text from run artifacts and metadata.
// All arguments are plain data — no filesystem reads here.
// runtimeVars: optional object of captured/derived variable values from the run.
export function generateRunReview({ workflowId, runDir, filled = [], skipped = [], errors = [], startUrl = '', dryRun = true, runtimeVars = null }) {
  const runId = runDir.split(/[\\/]/).pop() || runDir;

  const status = errors.length
    ? (filled.length ? 'PARTIAL SUCCESS — some fields failed' : 'FAILED')
    : dryRun ? 'DRY-RUN COMPLETE' : 'LIVE RUN COMPLETE';

  const filledLines = filled.length
    ? filled.map(f => `- **${f.field}** → \`${f.selector}\`: ${f.masked ? '[REDACTED]' : `"${String(f.value || '').slice(0, 120)}"`}`)
    : ['_None_'];

  const skippedLines = skipped.length
    ? skipped.map(s => `- **${s.field}**: ${s.reason}${s.selector ? ` (selector: \`${s.selector}\`)` : ''}`)
    : ['_None_'];

  const errorLines = errors.length
    ? errors.map(e => `- **${e.field}**: ${e.error}${e.selector ? ` (selector: \`${e.selector}\`)` : ''}`)
    : ['_None_'];

  const existingArtifacts = EXPECTED_ARTIFACTS.filter(f => exists(join(runDir, f)));
  const artifactLines = existingArtifacts.map(f => `- \`${f}\``);

  const ambiguities = buildAmbiguities(filled, skipped, errors);
  const recommendations = buildRecommendations(filled, skipped, errors);
  const runtimeVarLines = buildRuntimeVarSection(runtimeVars, skipped);

  const lines = [
    `# Run Review: ${workflowId}`,
    '',
    `**Run ID:** \`${runId}\``,
    `**Status:** ${status}`,
    `**Dry-run:** ${dryRun ? 'yes' : 'no'}`,
    `**Generated:** ${new Date().toISOString()}`,
    '',
    '---',
    '',
    '## What Browsy did',
    '',
    ...(startUrl ? [`- Navigated to: ${startUrl}`] : []),
    filled.length
      ? `- Filled **${filled.length}** field(s)${dryRun ? ' (dry-run — no real actions taken)' : ''}`
      : '- No fields were filled',
    skipped.length ? `- Skipped **${skipped.length}** field(s) for safety or missing values` : null,
    errors.length ? `- Encountered **${errors.length}** error(s)` : null,
    '',
    '## What worked',
    '',
    ...filledLines,
    '',
    '## What was skipped for safety',
    '',
    ...skippedLines,
    '',
    '## Errors',
    '',
    ...errorLines,
    '',
    ...runtimeVarLines,
    '## Ambiguities',
    '',
    ...ambiguities,
    '',
    '## Recommended next fix',
    '',
    ...recommendations,
    '',
    '## Artifacts',
    '',
    `Artifacts saved to: \`${runDir}\``,
    '',
    ...artifactLines,
    existingArtifacts.length < EXPECTED_ARTIFACTS.length
      ? `\n⚠ ${EXPECTED_ARTIFACTS.length - existingArtifacts.length} expected artifact(s) not found — run may have been incomplete.`
      : null,
    '',
    '---',
    `_Generated by Browsy run-review_`,
    ''
  ];

  return lines.filter(l => l !== null).join('\n');
}

function buildAmbiguities(filled, skipped, errors) {
  const items = [];

  const placeholderSelectors = filled.filter(f => f.selector && f.selector.includes('discovery'));
  if (placeholderSelectors.length) {
    items.push(`- ${placeholderSelectors.length} field(s) have placeholder selectors — run discovery with \`--candidates\` to find real ones.`);
  }

  const noValueSkipped = skipped.filter(s => s.reason.includes('no manifest value'));
  if (noValueSkipped.length) {
    items.push(`- ${noValueSkipped.length} field(s) had no value in the manifest: ${noValueSkipped.map(s => s.field).join(', ')}.`);
  }

  const selectorErrors = errors.filter(e =>
    /selector|locator|not found|timeout|element/i.test(e.error)
  );
  if (selectorErrors.length) {
    items.push(`- ${selectorErrors.length} field(s) failed with selector/locator errors — page DOM may have changed since discovery.`);
  }

  if (!items.length) items.push('_None — run looks clean._');
  return items;
}

function buildRuntimeVarSection(runtimeVars, skipped) {
  // Only emit the section if variables were declared or something is missing
  const missingVarSkipped = skipped.filter(s => s.reason?.startsWith('missing runtime variable'));
  if (!runtimeVars && !missingVarSkipped.length) return [];

  const lines = ['## Runtime variables', ''];

  if (runtimeVars && Object.keys(runtimeVars).length) {
    lines.push('Variables captured during this run:');
    lines.push('');
    for (const [k, v] of Object.entries(runtimeVars)) {
      lines.push(`- **${k}**: \`${v}\``);
    }
    lines.push('');
    lines.push(`_Written to \`runtime-vars.json\` in the run directory._`);
    lines.push('');
  } else if (!missingVarSkipped.length) {
    lines.push('_No runtime variables captured this run._');
    lines.push('');
  }

  if (missingVarSkipped.length) {
    lines.push('⚠ **Missing required runtime variables:**');
    lines.push('');
    for (const s of missingVarSkipped) {
      const varName = s.reason.replace('missing runtime variable: ', '');
      lines.push(`- \`${varName}\` — could not be captured from the page`);
    }
    lines.push('');
    lines.push('The run stopped safely because a required variable could not be resolved.');
    lines.push('Check that the page navigation succeeded and the URL or page text contains the expected value.');
    lines.push('');
  }

  return lines;
}

function buildRecommendations(filled, skipped, errors) {
  if (skipped.some(s => s.reason?.startsWith('missing runtime variable'))) {
    return [
      '1. A required runtime variable could not be captured — see **Runtime variables** section above.',
      '2. Verify the step that generates the ID completed successfully (check screenshots).',
      '3. Update the capture spec in `workflow.json` (correct `source`, `regex`, or `selector`).',
      '4. Re-run with `--dry-run` to confirm capture works before live mode.'
    ];
  }

  if (errors.some(e => /unresolved template variable/i.test(e.error))) {
    return [
      '1. A URL template could not be resolved — a required variable was not yet captured.',
      '2. Ensure the capture step runs before the navigation that uses the variable.',
      '3. Check `runtime-vars.json` to see which variables were captured.',
      '4. Update the workflow step order or capture spec as needed.'
    ];
  }

  if (errors.some(e => /selector|locator|not found|timeout/i.test(e.error))) {
    return [
      '1. Re-run discovery with `--candidates` to get updated selectors:',
      '   ```bash',
      '   npm run discover -- --workflow <id> --url <url> --candidates',
      '   ```',
      '2. Update `field-map.local.json` with the new recommended selectors.',
      '3. Re-run dry-run.'
    ];
  }

  if (skipped.filter(s => s.reason.includes('no manifest value')).length) {
    return [
      '1. Update `manifest.example.json` with real values for all fields.',
      '2. Re-run dry-run.'
    ];
  }

  if (errors.length) {
    return [
      '1. Check `errors.json` for full detail.',
      '2. Run with `BROWSY_DEBUG=1` for stack traces.',
      '3. Check whether the target page requires auth — run `npm run auth:save` if needed.'
    ];
  }

  if (!filled.length) {
    return [
      '1. Field map may be empty or missing.',
      '2. Ensure `workflows/<id>/field-map.local.json` exists with real selectors.',
      '3. Ensure `manifest.example.json` has values for all field sources.',
      '4. Re-run dry-run.'
    ];
  }

  return [
    '1. Review `filled-fields.json` — do the values look correct?',
    '2. Open `screenshot-after-fill.png` — does the page look right?',
    '3. If yes: complete the manual-only actions in the browser, then promote this workflow.',
    '4. If no: add plain-English feedback and re-run.'
  ];
}
