#!/usr/bin/env node
/**
 * Workflow runner: salesforce-reports
 * Goal: Download partner pipeline reports from salesforce
 *
 * Generated by Browsy v0.2 — review before first use.
 * Replace placeholder selectors in field-map.local.json before running against a real site.
 *
 * Usage:
 *   node workflows/salesforce-reports/run.mjs [--manifest path] [--dry-run] [--headed] [--no-pause] [--allow-final-action]
 */
import { parseArgs, boolArg } from '../../src/core/args.mjs';
import {
  loadWorkflowConfig, loadManifest, loadSafetyPolicy, loadFieldMap,
  createRunDir, createRunLogger, writeRunArtifact, saveScreenshot,
  recordFilledField, recordSkippedField, recordError, finalizeRun,
  getManifestValue
} from '../../src/core/workflow-runtime.mjs';
import { isDangerousText, isManualOnly } from '../../src/core/safety.mjs';
import { PlaywrightAdapter } from '../../src/adapters/playwright-adapter.mjs';

const WORKFLOW_ID = 'salesforce-reports';

const rawArgs = process.argv.slice(2);
const args = parseArgs(rawArgs);
const manifestPath = args.manifest || `workflows/${WORKFLOW_ID}/manifest.example.json`;
const dryRun = boolArg(args['dry-run'], true);
const headed = boolArg(args.headed, true);
const noPause = boolArg(args['no-pause'], false);
const allowFinalAction = boolArg(args['allow-final-action'], false);

if (!dryRun && !allowFinalAction) {
  console.log('[INFO] Running in live mode with dry-run=false.');
  console.log('[INFO] Final actions still require --allow-final-action AND explicit safety policy approval.');
}

const config = loadWorkflowConfig(WORKFLOW_ID);
const manifest = loadManifest(manifestPath);
const policy = loadSafetyPolicy(WORKFLOW_ID);
const fieldMap = loadFieldMap(WORKFLOW_ID);

const runDir = createRunDir(WORKFLOW_ID);
const logger = createRunLogger(runDir);

logger.log('info', `Workflow: ${WORKFLOW_ID}`, { dryRun, headed, manifestPath, runDir });

const filled = [];
const skipped = [];
const errors = [];
const adapter = new PlaywrightAdapter();

try {
  await adapter.open({ headed, storageState: `.auth/${WORKFLOW_ID}.json`, dryRun });

  const startUrl = config.targets?.start_url || 'https://d2l.okta.com/app/UserHome';
  if (!startUrl) throw new Error('No start_url in workflow.json. Set targets.start_url.');

  logger.log('info', 'Navigating to: ' + startUrl);
  await adapter.page.goto(startUrl, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await adapter.snapshot(runDir, 'screenshot-start.png');

  writeRunArtifact(runDir, 'page-text-snapshot.txt', await adapter.text());
  writeRunArtifact(runDir, 'html-snapshot.html', await adapter.html());

  const fields = Object.entries(fieldMap.fields || {});
  if (!fields.length) {
    logger.log('warn', 'Field map is empty. Run discovery and create field-map.local.json.');
  }

  for (const [fieldName, fieldConfig] of fields) {
    const { selector, type, source, safety_category, redact } = fieldConfig;

    // Safety: skip manual-only fields
    if (safety_category && isManualOnly(safety_category, policy)) {
      logger.log('info', `Skipped (manual-only: ${safety_category}): ${fieldName}`);
      recordSkippedField(skipped, fieldName, `manual-only: ${safety_category}`, selector);
      continue;
    }

    // Safety: skip buttons with dangerous text
    if ((type === 'button' || type === 'submit') && isDangerousText(fieldName, policy)) {
      logger.log('info', `Skipped (dangerous text): ${fieldName}`);
      recordSkippedField(skipped, fieldName, 'dangerous text', selector);
      continue;
    }

    const value = getManifestValue(manifest, source);
    if (value === undefined || value === null) {
      if (source) {
        logger.log('warn', `No value in manifest for: ${fieldName} (source: ${source})`);
      }
      recordSkippedField(skipped, fieldName, `no manifest value (source: ${source || 'none'})`, selector);
      continue;
    }

    if (dryRun) {
      logger.log('info', `[DRY-RUN] Would ${type} "${fieldName}" = ${redact ? '[REDACTED]' : JSON.stringify(value)}`, { selector });
      recordFilledField(filled, fieldName, selector, value, !!redact);
      continue;
    }

    try {
      if (type === 'text' || type === 'email' || type === 'url') {
        await adapter.fill(selector, value);
      } else if (type === 'textarea') {
        await adapter.fill(selector, value);
      } else if (type === 'select') {
        await adapter.selectOption(selector, value);
      } else if (type === 'file') {
        await adapter.upload(selector, value);
      } else if (type === 'checkbox') {
        await adapter.setChecked(selector, Boolean(value));
      } else {
        logger.log('warn', `Unsupported field type "${type}" for ${fieldName}`);
        recordSkippedField(skipped, fieldName, `unsupported type: ${type}`, selector);
        continue;
      }
      logger.log('info', `Filled: ${fieldName}`, { selector, type });
      recordFilledField(filled, fieldName, selector, value, !!redact);
    } catch (err) {
      logger.log('error', `Failed to fill ${fieldName}: ${err.message}`, { selector });
      recordError(errors, fieldName, err, selector);
    }
  }

  await adapter.snapshot(runDir, 'screenshot-after-fill.png');
  logger.log('info', 'Fill phase complete. Browser paused for manual review.');

  if (!noPause && (dryRun || policy.pause_at_end_default)) {
    console.log('');
    console.log('--- MANUAL CHECKPOINT ---');
    console.log('Review the browser. Complete any manual-only actions.');
    console.log('Close the browser window to end the run.');
    await adapter.waitForClose();
  } else {
    await adapter.close();
  }

} catch (err) {
  logger.log('error', 'Workflow error: ' + err.message);
  recordError(errors, 'workflow', err);
  await adapter.close().catch(() => {});
} finally {
  finalizeRun(runDir, { logger, filled, skipped, errors });
}
